[env:az-delivery-devkit-v4]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
lib_deps =
  Time
  Timezone
  Adafruit GFX Library
  Adafruit MQTT Library
  NTPClient
  MD_REncoder
  BH1750
  Adafruit BME280 Library
  DFRobotDFPlayerMini
upload_protocol = espota
upload_port = 192.168.0.132